wrote code, added tests
zhenechkaaaa/OOP pull request #1
Opened 2024-09-08 13:20 UTC by zhenechkaaaa

2024-09-09 08:57 UTC, shadrina commented
Возможно, проверки не проходят из-за неправильного названия pull request'а.

2024-09-10 08:13 UTC, shadrina requested changes

2024-09-10 08:13 UTC, shadrina commented on Task_1_1_1/src/test/java/nsu/odnostorontseva/HeapSortTest.java
> +    void main_check() {
В Java у нас `camelCase`. См. Google Java Style Guide

2024-09-10 14:36 UTC, zhenechkaaaa commented
![изображение](https://github.com/user-attachments/assets/9df2d4db-8314-4c47-b085-c58b9977704e)
made a graph

2024-09-11 03:24 UTC, zhenechkaaaa commented
![Снимок экрана от 2024-09-10 21-12-29](https://github.com/user-attachments/assets/e80d8b27-9a81-4d2a-a9e5-d954baeb2140)
made a graph

2024-09-24 08:33 UTC, shadrina approved these changes

2024-10-29 06:14 UTC, merged